package app.controllers;

import java.util.concurrent.atomic.AtomicLong;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import app.models.User;
import app.repositories.UserRepository;

@RestController
@RequestMapping("/user")
public class UserController {
	private final AtomicLong counter = new AtomicLong();

	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired 
	private UserRepository userRepository; 

	@RequestMapping("/") 
	public String showHello(){
		return "Hello User";
	}

	@RequestMapping(method = RequestMethod.GET)
	public User getUserById(@RequestParam(name = "id") long userId) {
		return userRepository.findOne(userId);
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {	
		return userRepository.findAll();
	}

	@GetMapping(path="/add") 
	public @ResponseBody String setUser() {
		User user = new User();
		user.setUserId(counter.incrementAndGet());
		user.setName("Anju");
		user.setAge(33);
		user.setAddress("Vazhakkala");
		userRepository.save(user);
		return "Saved User";
	}
}
